### ISSUE TITLE
UI-bugs: settings

### ISSUE THREAD

**Issue by Liisign** [ZeRuS04/FeedYourCat#1]
![image](https://github.com/ZeRuS04/FeedYourCat/assets/162809214/935726ff-d750-4f92-a8e0-8f15fd9b28f9)

1) Сжимается и сдвигается икнока "назад" в настройках.
Шаги воспроизведения:
- зайти в настройки
- переключить язык
Проверены: обе точки входа, любой язык на стартке - баг стабилен.
Баг сбрасывается при выходе из настроек и при повторном входе (игру перезапускать не надо)

2) Слишком активные тени на свитчах

3) В макете предусмотрено переключение "наоборот": иконка на свитче означает, что **_это_** будет включено, если передвинуть свитч на место иконки. То есть в темной теме видим иконку солнышка. В целом это серый паттерн, неопределенность которого решается только контекстно (у нас с этим все ок - на экране сразу виден результат). Но поменять местами нужно, потому что в нашем случае иконка не описывает состояние (для этого есть мгновенная смена контекста), а означает действие.

4) Иконки на свитчах в низком качестве. Могу выгрузить любой необходимый формат, например svg, а цвет пропишем переменной.

5) На качельке громкости в крайних положениях иконки должны меняться на заполненные аналоги.

**Comment by ZeRuS04** [comment]
1,2,3,5 - ок
4 - странно, я svg использую, поищу в чем причина

**Comment by ZeRuS04** [comment]
Done.
