### ISSUE TITLE
Стили

### ISSUE THREAD

**Issue by Liisign** [ZeRuS04/FeedYourCat#3]
<img width="634" alt="image" src="https://github.com/ZeRuS04/FeedYourCat/assets/162809214/03f959c6-282e-4d93-8b2f-e864ecc33261">

1) Счет (сами цифры) на макете в другом шрифте, это на всех экранах, в том числе на паузе
2) Иконки навигации в шапке (и счет) имеют другой цвет в макете, менее яркий. В макете это достигается за счет общей прозрачности на слое хэдера.
3) В светлой теме не виден градиент на фоне (от светлого верха к темному низу). В темной теме все ок.

___

В макете предполагается немного другая навигация при клике на паузу: сразу включаем экран паузы с кнопками. А при клике на "настройки" - сразу настройки. (Этой иконки нет в последнем билде) По иконке "назад" из настроек попадаем туда, откуда пришли, в зависимости от точки входа. Но возможно текущий подход лучше и проще в реализации, потому что игра не продолжается внезапно. Надо обсудить на созвоне: либо навигацию оставлять как есть, либо добавлять экран с countDown в подходе по макету.

**Comment by ZeRuS04** [comment]
В хедере голова кота тоже прозрачная слегка?

Со шрифтами - баг в принципе что они не подгрузились в ассеты, буду исправлять

**Comment by Liisign** [comment]
Да, прозрачность на весь контент слоя

**Comment by ZeRuS04** [comment]
Градиент в светлой теме есть, он просто не очень явный, но явнее сделать не могу.
На счет навигации можно созвониться обсудить.
В остальном пофиксил.
